import { Router } from 'express';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import roleRoutes from './role.routes';
import permissionRoutes from './permission.routes';
import auditRoutes from './audit.routes';
import embassyRoutes from './embassy.routes';
import serviceTypeRoutes from './service-type.routes';
import serviceRequestRoutes from './service-request.routes';
import profileRoutes from './profile.routes';
import visaRoutes from './visa.routes';
import visaDocumentRoutes from './visa-document.routes';
import visaDecisionRoutes from './visa-decision.routes';
import appointmentRoutes from './appointment.routes';
import legalizationRoutes from './legalization.routes';
import emergencyRoutes from './emergency.routes';
import diplomaticRoutes from './diplomatic.routes';
import financialRoutes from './financial.routes';
import dashboardRoutes from './dashboard.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/permissions', permissionRoutes);
router.use('/audit', auditRoutes);
router.use('/embassies', embassyRoutes);
router.use('/service-types', serviceTypeRoutes);
router.use('/service-requests', serviceRequestRoutes);
router.use('/profile', profileRoutes);
router.use('/visa', visaRoutes);
router.use('/visa/documents', visaDocumentRoutes);
router.use('/visa/decisions', visaDecisionRoutes);
router.use('/appointments', appointmentRoutes);
router.use('/legalization', legalizationRoutes);
router.use('/emergency', emergencyRoutes);
router.use('/diplomatic', diplomaticRoutes);
router.use('/financial', financialRoutes);
router.use('/dashboard', dashboardRoutes);

export default router;